#!/usr/bin/env bash

JAVA_MAJOR=1
JAVA_MINOR=8
APP_JAR="PLUGINS/LAUNCHER.JAR"
APP_NAME="IMPAX EE CD Viewer for MAC"
VM_ARGS="-XX:+UseSerialGC -Xms384m -Xmx384m -Dosgi.framework=PLUGINS/OSGI.JAR -Dosgi.configuration.area=@none -Dosgi.bundles=ocommon@2:start,oconfig@3:start,oruntime@start -Dsun.java2d.ddoffscreen=false"

# Set the working directory to be CD/DVD root
cd "$(dirname "$0")/../../../"

# Error message for NO JAVA dialog
ERROR_TITLE="Cannot launch $APP_NAME"
ERROR_MSG="$APP_NAME benoetigt Java version $JAVA_MAJOR.$JAVA_MINOR oder neuer."
DOWNLOAD_URL="http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html"


# Is Java installed?
if type -p java; then
    _java="java"
elif [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]]; then
    _java="$JAVA_HOME/bin/java"
else
    osascript \
	-e "set question to display dialog \"$ERROR_MSG\" with title \"$ERROR_TITLE\" buttons {\"Cancel\", \"Download\"} default button 2" \
	-e "if button returned of question is equal to \"Download\" then open location \"$DOWNLOAD_URL\""
	echo "$ERROR_TITLE"
	echo "$ERROR_MSG"
	exit 1
fi

# Java version check
if [[ "$_java" ]]; then
    version=$("$_java" -version 2>&1 | awk -F '"' '/version/ {print $2}')
    if [[ "$version" < "$JAVA_MAJOR.$JAVA_MINOR" ]]; then
        osascript \
    	-e "set question to display dialog \"$ERROR_MSG\" with title \"$ERROR_TITLE\" buttons {\"Cancel\", \"Download\"} default button 2" \
    	-e "if button returned of question is equal to \"Download\" then open location \"$DOWNLOAD_URL\""
       	echo "$ERROR_TITLE"
    	echo "$ERROR_MSG"
    	exit 1
    fi
fi

# Run the application
exec $_java  $VM_ARGS -Dapple.laf.useScreenMenuBar=true -Dcom.apple.macos.use-file-dialog-packages=true -Xdock:name="$APP_NAME" -Xdock:icon="./CDViewerMac/Contents/Resources/Agfa.icns" -jar "$APP_JAR" -application com.agfa.pacs.login.LoginManager -clear